namespace V3RttMonitor.Core.Protocol;

public sealed class RttFieldDescriptor(
    int index,
    string key,
    string displayName,
    string unit,
    string group,
    string format,
    bool integerLike = false,
    string? colorHex = null)
{
    public int Index { get; } = index;
    public string Key { get; } = key;
    public string DisplayName { get; } = displayName;
    public string Unit { get; } = unit;
    public string Group { get; } = group;
    public string Format { get; } = format;
    public bool IntegerLike { get; } = integerLike;
    public string? ColorHex { get; } = colorHex;
    public bool IsAutoGenerated { get; init; }
}

/// <summary>
/// The binary stream only reveals channel indexes. Names, units, groups and plot layout
/// are intentionally supplied by an Excel template instead of being guessed here.
/// </summary>
public static class RttFieldCatalog
{
    public static IReadOnlyList<RttFieldDescriptor> GetAll(int floatCount)
    {
        if (floatCount < 0) throw new ArgumentOutOfRangeException(nameof(floatCount));
        return Enumerable.Range(0, floatCount)
            .Select(index => new RttFieldDescriptor(
                index,
                $"CH_{index}",
                $"通道 {index}",
                "",
                "未配置",
                "G7")
            {
                IsAutoGenerated = true,
            })
            .ToArray();
    }

    public static IReadOnlyList<RttFieldDescriptor> All => GetAll(JustFloatParser.DefaultFloatCount);
}
