<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\V3RttMonitor.Core\V3RttMonitor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CanKit.Core" Version="0.5.6" />
    <PackageReference Include="CanKit.Adapter.Virtual" Version="0.5.6" />
    <PackageReference Include="CanKit.Adapter.ZLG" Version="0.5.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
